### ISSUE TITLE
Hangman

### ISSUE THREAD

**Issue by bhangalepiyush** [dragonfire535/xiao#11]
I Tried Hangman Command to be added on my Bot! But when i did that its telling 
, Oh no, an error occurred: 401 Unauthorized. Try again later!
What to do?
Having This Issue
- Xiao version: latest
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while self-hosting the bot.
  - Node.js version: Latest
  - Commit hash:
  - Operating system: VPS Glitch.com

**Comment by dragonfire535** [comment]
Did you enter a Wordnik API key?

**Comment by bhangalepiyush** [comment]
I did

**Comment by bhangalepiyush** [comment]
But instead of process.env i did 
const { WORDNIK_KEY} = 'key here'

**Comment by dragonfire535** [comment]
That's not how JavaScript works, you're trying to destructure a string literal. 

As this isn't an issue with the bot but with your knowledge of JavaScript, I'll close.
