### ISSUE TITLE
Various errors in the "mafia" and "wizard-convention" commands.

### ISSUE THREAD

**Issue by bullfrog0981** [dragonfire535/xiao#21]
Got this error while trying to play mafia and wizard= players.filterArray is not a function

**Comment by bullfrog0981** [comment]
tried it again, we got through the voting but then got this error = "Cannot read property 'id' of undefined"

**Comment by dragonfire535** [comment]
Try again with the latest commit. These commands are rarely used so it's been hard to get testers for them, good thing you showed up.

**Comment by bullfrog0981** [comment]
lol, no problem imma go test it now

**Comment by bullfrog0981** [comment]
Ok, when i try to heal the game closes and puts the error "Cannot read property 'id' of undefined" out again, same thing happens when the mafia try to kill someone

**Comment by dragonfire535** [comment]
Try the latest fix.

**Comment by bullfrog0981** [comment]
Question how long is the game? Because after the first round of votes and the first hanging/expelling, the game end with "Oh no, the dragon wasn't caught in time... Nice job, @user"

**Comment by dragonfire535** [comment]
How many players did you have?

**Comment by bullfrog0981** [comment]
3

**Comment by dragonfire535** [comment]
The game ends if there's only 2 players left, as the dragon + one user are all that's left, and that's either gonna be an infinite stalemate (if it's just the dragon and the healer) or a guaranteed kill (as there's no one to save the remaining player).

**Comment by bullfrog0981** [comment]
ok, with 4 players playing we got the error "Cannot read property 'id' of undefined" after choosing someone to save

**Comment by dragonfire535** [comment]
Did you get the latest fix? Make sure you're on the very latest, I made a small update recently.

**Comment by bullfrog0981** [comment]
oh, i didn't lol. Lemme go update it

**Comment by bullfrog0981** [comment]
Thanks! Last commit works like a charm

**Comment by dragonfire535** [comment]
Awesome!
