### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by JesterOC3** [dragonfire535/xiao#22]
Hey, just stumbled upon Xiao and it looks great feature wise.
However i couldn't set it up.. installing canvas dependencies using the command:

apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

**results in this:**
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package build-essential
E: Unable to locate package libcairo2-dev
E: Unable to locate package libpango1.0-dev
E: Couldn't find any package by glob 'libpango1.0-dev'
E: Couldn't find any package by regex 'libpango1.0-dev'
E: Unable to locate package libjpeg-dev
E: Unable to locate package libgif-dev
E: Unable to locate package librsvg2-dev

Hope u can help.
Thanks for your time.

**Comment by dragonfire535** [comment]
Android is not something I plan on guaranteeing support for. If it ever becomes able to run it, that's fine, but I'm not going to actively make sure it's possible, nor advocate it's usage.
