### ISSUE TITLE
Translate Command

### ISSUE THREAD

**Issue by Ja1rus3** [dragonfire535/xiao#23]
How about a new translate command using > npm i google-translate-api?

**Comment by dragonfire535** [comment]
I fail to see what advantages using `google-translate-api` would bring over using the current Yandex API, especially since one isn't necessarily advised, while the other is API-key based and 100% advised.

**Comment by dragonfire535** [comment]
Yes, but that's not exactly a valid argument. The Yandex API is also free with a quota limit, and with Xiao there's no reason it should ever hit the quota (if you're translating that much you're crazy, and if you released it publicly you're violating the terms of almost every bot list).

**Comment by Ja1rus3** [comment]
Oh ok
