### ISSUE TITLE
ypeError: user.displayAvatarURL is not a function

### ISSUE THREAD

**Issue by Ja1rus3** [dragonfire535/xiao#24]
![image](https://user-images.githubusercontent.com/43052908/48654254-446d7800-e9d9-11e8-9da3-c0ee0f1d0dcf.png)
"@󠀀󠀀 󠀀󠀀󠀀󠀀 󠀀󠀀._Rain Shadow, An error occurred while running the command: TypeError: user.displayAvatarURL is not a function
You shouldn't ever receive an error like this."

^ This is what the bot replies with every time I try to use the avatar-edit commands... what does it mean?

**Comment by dragonfire535** [comment]
I can't reproduce on my end, which means it's something you did. My guess is you're on stable discord.js and not master, but if you ran the install instructions properly that shouldn't happen.

**Comment by Ja1rus3** [comment]
oh ok

**Comment by Ja1rus3** [comment]
didnt work ;-;

**Comment by dragonfire535** [comment]
Your issues would be better placed [on the official server](https://discord.gg/sbMe32W), as this is most certainly not an issue with the bot itself.

**Comment by Ja1rus3** [comment]
mk
