### ISSUE TITLE
reproducible issue when using the 'manga' command

### ISSUE THREAD

**Issue by meleu** [dragonfire535/xiao#26]
Using xiao on its own server (Dragon Fire Official),

when I use the `manga` command, everytime I look for `gen` I get `Cannot read property 'replace' of null.`

![genbug](https://user-images.githubusercontent.com/8508804/49588403-bf2d1180-f94d-11e8-9db8-7fd698ac43b9.png)

**Comment by dragonfire535** [comment]
Fixed in the latest commit.
