### ISSUE TITLE
Misleading project description

### ISSUE THREAD

**Issue by cloudrex** [dragonfire535/xiao#29]
I suggest you change your GitHub project description from "Your personal server companion." to "Your personal Discord server companion."

**Comment by dragonfire535** [comment]
You'd REALLY have to be blind to avoid the huge number of tags with "discord" in them, but okay.

**Comment by cloudrex** [comment]
That's better!

![image](https://user-images.githubusercontent.com/41349879/55159541-a3858b00-5137-11e9-81e5-f451ec2fa46a.png)
