### ISSUE TITLE
jimp instead of canvas

### ISSUE THREAD

**Issue by saanuregh** [dragonfire535/xiao#34]
Love your project!!! I have a personal discord bot for a private small server based off your project.

There is this image manipulation library very similar to canvas, but has zero native dependencies called jimp.
link: https://www.npmjs.com/package/jimp
I was wondering if there is a reason why you prefer canvas instead of jimp. And if you need help with converting the code to use jimp instead of canvas 😊.

**Comment by dragonfire535** [comment]
canvas is preferred mainly due to speed, being a native app, it has a significant performance advantage. It's also a more mainstream API, due to being present in web browsers.

**Comment by NightYoshi370** [comment]
@saanuregh why do you want to use jimp?
I've used it and trust me: writing code in it is uglier than writing code in canvas

**Comment by saanuregh** [comment]
@NightYoshi370 i did a test run just nw ( i use windows so installing canvas needs a little more work).
1. No ttf font support, fonts need to be converted to fnt (lot of work, also reduces flexibility)
2. Performance kinda seems same in usage.
3. You can only code either by promises or callbacks, but its not that ugly for any particular command code.
