### ISSUE TITLE
Translator

### ISSUE THREAD

**Issue by saanuregh** [dragonfire535/xiao#35]
https://github.com/k3rn31p4nic/google-translate-api
Lets you use google translate for free.

**Comment by Androz2091** [comment]
Personally I prefer the `deepl-scraper` package which offers a much better translation quality

**Comment by saanuregh** [comment]
but supports way less language, no chinese or asian languages

**Comment by Androz2091** [comment]
Yes, it's true.
Dragonfire has to decide what is best for Xiao:
- many supported languages but of much lower quality
- less language but of great
 quality

¯\_(ツ)_/¯

**Comment by dragonfire535** [comment]
What's wrong with Yandex? I don't see much reason to change.

**Comment by Androz2091** [comment]
It requires an API key, it's not the easiest to install...
In addition to the translation level, I find that it's not as good as Google.
Deepl is great : good traduction quality, easy to install!

**Comment by Androz2091** [comment]
https://github.com/Androz2091/AtlantaBot/blob/master/commands/General/translate.js

**Comment by Androz2091** [comment]
https://github.com/Androz2091/AtlantaBot/blob/master/commands/General/translate.js

**Comment by saanuregh** [comment]
- yandex is pretty bad for asian languages
- deepl-scraper uses a headless chrome API while the google one uses just HTTP requests

**Comment by Androz2091** [comment]
Effectively deepl scraper uses chromium which makes it heavier.
Then I think you'll agree that the translation is of a much better quality 
Anyway yandex it's really not great because it requires an API key for a lower quality...

**Comment by dragonfire535** [comment]
Headless chrome is way too heavy for one command. Google Translate maybe, but I don't want to use anything that uses Headless Chrome.

**Comment by Androz2091** [comment]
All right, I can understand.
I think you're not without knowing it, but the translation quality of yandex and Google are just... crappy ? :sweat_smile:

After that it remains a fun command so a translation by Google is quite correct for this usage

**Comment by dragonfire535** [comment]
As of 2702cd989776f0723b5ef1da5300c78cf43efeca, this has been implemented. Google Translate is now used rather than Yandex.
