### ISSUE TITLE
great bot

### ISSUE THREAD

**Issue by modyamash** [dragonfire535/xiao#40]
**Please describe the problem you are having in as much detail as possible:**

**Further details:**
- Version:
- Priority this issue should have – **please be realistic and elaborate if possible**:

- [ ] I found this issue while self-hosting the bot.
  - Node.js version: v13.6.0
  - Commit hash: v13.6.0
  - Operating system: windows 10 x64
Evry time i try pm2 i get this erorr but its working fine with
node Xiao.js !
please some help and  thank you for share this awesome bot :)
![2020-01-24_6-46-21](https://user-images.githubusercontent.com/59402874/73038758-42643c00-3e5c-11ea-87a6-71c8ca4e837a.jpg)

**Comment by chroventer** [comment]
From what I can gather, it's a permission issue; run the command prompt or PowerShell window as administrator and you should be good to go.

**Comment by modyamash** [comment]
> From what I can gather, it's a permission issue; run the CMD or PowerShell window as administrator and you should be good to go.
thank you very mutch its working  fine now :) 
but  Is there any way to auto delete command usage ? 👯‍♂

**Comment by Androz2091** [comment]
No there's no option by default in the Commando library to automatically delete command messages. You can implement it by forking Commando and updating your own xiao project dependencies or you have to add `message.delete()` in each command file.

**Comment by modyamash** [comment]
thank you  for your help maybe that  work fine  :) thank you very mutch for  this  great  bot  :) i'll  trun close this  issue  its  totaly  fine  right now  and also great bot <3

**Comment by thewolf87** [comment]
Please give me imgur album IDs I request you I don't know how to get them pleaseeeee
