### ISSUE TITLE
Error: FFmpeg/avconv not found!

### ISSUE THREAD

**Issue by Overtime2005** [dragonfire535/xiao#48]
**Please describe the problem you are having in as much detail as possible:**
everytime I run the airhorn command I get this

**Further details:**
- Version:
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I found this issue while self-hosting the bot.
  - Node.js version:
  - Commit hash:
  - Operating system:

**Comment by dragonfire535** [comment]
You probably forgot to install ffmpeg correctly, or installed it wrong. Check back over the [install instructions](https://github.com/dragonfire535/xiao#installing) and see if you missed anything.

**This issue tracker should be used for bugs, not support. If you need support, use the [official Discord server](https://discord.com/invite/mTr83zt) instead.**
