### ISSUE TITLE
A Timeout function in mp games, if no response by users

### ISSUE THREAD

**Issue by FirezzzZ** [dragonfire535/xiao#49]
**Is your feature request related to a problem? Please describe.**
the mp games dont have a timeout, like if the both the users go offline the bot still sends the messages.

**Describe the ideal solution**
i want the bot to stop the game if there is no response by both the users for 2 times.
and say like `game over, nobody responded`

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by FirezzzZ** [comment]
tic-tac-toe to be specific

**Comment by dragonfire535** [comment]
This has been implemented as of ae543b79c788e3840e1cc64fb2c31ce78154bab1.
