### ISSUE TITLE
error in quizduel game and maybe other mp games

### ISSUE THREAD

**Issue by FirezzzZ** [dragonfire535/xiao#51]
**Please describe the problem you are having in as much detail as possible:**
so basically after my recent issue, you have updated the code but, when the users enter wrong answers, it says that the answer is incorrect and the msgs.size becomes `0` in console and then sends Game Ended Due to Inactivity, which should not happen
pleas check with other mp commands too, i dont use class with extend so i have edited the code(not the main functions) check my code
[https://hasteb.in/kojadana.coffeescript](url) (copy it)

**Comment by dragonfire535** [comment]
Try bf18bec4357ad9c1e607572ef63d5c782f52414a

**Comment by dragonfire535** [comment]
I just tested it myself, this has been resolved.

**Comment by FirezzzZ** [comment]
`TypeError: Cannot read property 'author' of undefined` 
after adding the new code at line
```js
        const userWin = result.author.id === message.author.id;
``` my code (do check) -- https://hasteb.in/farofece.coffeescript
