### ISSUE TITLE
Voicemail for phonecall command

### ISSUE THREAD

**Issue by FirezzzZ** [dragonfire535/xiao#54]
**Is your feature request related to a problem? Please describe.**
will u try to make a voicemail command as it can be a really good and unique feature
**Describe the ideal solution**
this will require a db, ik u are against db's still it might be worth it as i have never seen a bot sending voicemail. users can see the voicemails with a command. up to you if u want to! if you are willing to this i prefer `quick.db`

**Comment by dragonfire535** [comment]
This doesn't necessarily need a DB. Just send the voicemail message to the channel after the call times out.

**Comment by FirezzzZ** [comment]
i was thinking that store them somewhere so the user who didnt pick up can see it later, but nvm do as you wish

**Comment by dragonfire535** [comment]
Added in 0c04ae9013511c15f543dc16a8cfc9f40c2d692b.
