### ISSUE TITLE
image by command generating

### ISSUE THREAD

**Issue by DemonRem** [dragonfire535/xiao#65]
**Is your feature request related to a problem? Please describe.**
No

**Describe the ideal solution**
in NSFW Channel after you put an image command the bot will generate a image in following time like 5-10 seconds

**Additional context**
the idea is the make the bot in nsfw channel after entering some image command , the bot
will generate image by the following command for each time like 5 sec by defulat and be option to change
the time too before the bot will generate a new image

**Comment by dragonfire535** [comment]
This would be very spammy on the Discord API.
