### ISSUE TITLE
this.client.games.get , get's property is undefined

### ISSUE THREAD

**Issue by SurgicalCrow** [dragonfire535/xiao#67]
this.client.games.get , get's property is undefined
this.client.games.set , sett's property is undefined
this.client.games.delete , delete's property is undefined

please tell me, i was trying to add some games in my bot

**Comment by dragonfire535** [comment]
This issue tracker is for bugs with Xiao, not for errors you get when copying commands onto your own bot. If you don't understand what you're copying, don't copy it.
