### ISSUE TITLE
Asking a new roleplay command

### ISSUE THREAD

**Issue by EMPERRORPK007** [dragonfire535/xiao#69]
Hey Bro. I have been inspired by your bot's image manipulation a lot. I have read all the commands and I used some of the commands in my bot too. I am recommending you adding a new roleplay command. I have added it in my bot and recommending you too. 
**it is called called NOM. that is , biting others in angry.**

I hope it helps.
thankyou.
for example see this gif.

![](https://cdn.discordapp.com/attachments/748829115603353621/754578380015534171/epSkltQ.gif)

**Comment by EMPERRORPK007** [comment]
sorry for my bad english

**Comment by dragonfire535** [comment]
This has been implemented in e7dfc864ec1cc38af1fd68a1c5977030df4dd5c2.
