### ISSUE TITLE
please hide nsfw commands in help command

### ISSUE THREAD

**Issue by yuu0007** [dragonfire535/xiao#76]
**Is your feature request related to a problem? Please describe.**
Please hide nsfw commands in the help command because there are some _karens_ in my server complaining about that.

**Describe the ideal solution**
Replace the nsfw commands in the help command with nothinh

**Describe alternatives you've considered**
none

**Additional context**

**Comment by dragonfire535** [comment]
Implemented in a810bd793c258ddf9d0a54a6579ab220dd670cb4.

**Comment by yuu0007** [comment]
ty
