### ISSUE TITLE
Last Man Standing Command

### ISSUE THREAD

**Issue by Lowkik-Sai** [dragonfire535/xiao#77]
Add contests category and command like you structure LAST MAN STANDING and GUESS THE NUMBER for **Surgical Crow**,
And i also want to know how to code these commands 
LMS - If there is no message after last message for 30 seconds then he won!
GTN - The member guesses the number is the winner!
lmsinfo,lmswinners,lms,etc...

**Comment by dragonfire535** [comment]
We have guess the number. Last Man Standing is a neat idea but I'd need to work on that execution as I'm not sure how just making sure you send a message every 30 seconds is very challenging or fun.

Not sure what Surgical Crow is.

**Comment by Lowkik-Sai** [comment]
> We have guess the number. Last Man Standing is a neat idea but I'd need to work on that execution as I'm not sure how just making sure you send a message every 30 seconds is very challenging or fun.
> 
> Not sure what Surgical Crow is.

Alright,if you know surgical crow
He created bot and he told that credits for last man standing is Dragon fire and surgical crow.
And this contests is makes our server active and its like survival...

**Comment by Lowkik-Sai** [comment]
Last Man Standing code will be created like LASTMESSAGEID = MESSAGEID ...and timeout x second like 30000

**Comment by Lowkik-Sai** [comment]
I have code for last man standing but i am not so much develoler.
Code : Outside the functions:
let giveawayActive = true;
let giveawayChannel = 'channelID';
let lastMessageID = '';


In the on message event:
if (message.channel.id === giveawayChannel) {
    if (giveawayActive) {
        lastMessageID = message.id;
        setTimeout(CheckWinner, 30000, message);
    }
}


CheckWinner function:
function CheckWinner(msg) {
    if (msg.id === lastMessageID) {
        giveawayActive = false;
        msg.reply(`Congratulations ${message.author}, you won the giveaway!`);
    }
}

**Comment by Lowkik-Sai** [comment]
Can you add Tambola Game/Housie game in India?
Like if we type prefix + ticket in specific channel,then bot will send an ticket to user with 25 number ,3rows,each row contains 5 numbers from 1-90 
And if admin or bot owner type prefix + tambolaroll + number of rolls (ex : ?tambolaroll 90 numbers or ?tambolaroll all) then bot starts rolling numbers and if any of the rolled number is in any of the use ticket,bot makes wrong on that number...like this i have some more ideas on contest to develop discord server active

**Comment by SurgicalCrow** [comment]
> > We have guess the number. Last Man Standing is a neat idea but I'd need to work on that execution as I'm not sure how just making sure you send a message every 30 seconds is very challenging or fun.
> > Not sure what Surgical Crow is.
> 
> Alright,if you know surgical crow
> He created bot and he told that credits for last man standing is Dragon fire and surgical crow.
> And this contests is makes our server active and its like survival...
> And where is guess the number code dude?

Who the hell are you? You are not either allowed to ask developers to make LAST MAN STANDING contest, its an unique idea of our team

**Comment by SurgicalCrow** [comment]
DragonFire knows that I am using some of his commands, doesn't mean that everything in the bot is made by DragonFire, I have given him credits for his commands (I have converted them to TS Though), my bot isn't a A to Z xiao copy, so @Lowkik-Sai think multiple times before saying something in a public repo against me

**Comment by SurgicalCrow** [comment]
> We have guess the number. Last Man Standing is a neat idea but I'd need to work on that execution as I'm not sure how just making sure you send a message every 30 seconds is very challenging or fun.
> 
> Not sure what Surgical Crow is.

**just making sure you send a message every 30 seconds is very challenging or fun.**

Answer: It's not something like that you are thinking, people will just keep chatting in the general chat, if the chat stops for 30 seconds, **[No one sends any message within 30 secs after the last message was sent then the author of the last message will win]**, then the author of the last message will be the grand winner.

**Comment by Lowkik-Sai** [comment]
Hold on @SurgicalCrow !
I didnt blame you and i dont ask you the help,I just ask him to help to make that code.
You also mind it before spoke!
I know the code for LMS but not developed more so i came here for Dragon Fire help🙂

**Comment by SurgicalCrow** [comment]
> 
> 
> Hold on @SurgicalCrow !
> I didnt blame you and i dont ask you the help,I just ask him to help to make that code.
> You also mind it before spoke!
> I know the code for LMS but not developed more so i came here for Dragon Fire help🙂

Sounds very poor, you know how to code but came here for someone's help, DragonFire is not here to code games for you nor supports self-hosting.

@dragonfire535 be aware of him, he is a scammer on discord, scamming discord servers owners, and pretending to be a staff of gaming organization, 

[Attachment / Proof](https://media.discordapp.net/attachments/781803613357473832/781808500379484190/unknown.png)

**Comment by LEGENDARY-KING** [comment]
@dragonfire535 Hey! I am the proud owner, Creator of Last Man Standing Contest
Im the sole owner of the Last Man Standing contest
Also please ignore @Lowkik-Sai ,

**Comment by Lowkik-Sai** [comment]
@LEGENDARY-KING @SurgicalCrow You guys dont know what loss happened to me and how you guys just say i am scammer 🤔
Dont you want to know the situation!
Stop here!

**Comment by Lowkik-Sai** [comment]
Don't be proud yourself among all!

**Comment by dragonfire535** [comment]
What in the world.

**Comment by Lowkik-Sai** [comment]
Nothing Ignore their words and everything,Just Misguiding

**Comment by dragonfire535** [comment]
First of all, no one "owns" the right to make a command this simple. If It were more interesting I'd add it without hesitation but I don't see the actual merit in doing so right now as it doesn't really seem all that fun. Obviously credit where credit is due but even if I had made it, no one "owns" the right to this idea and I probably wouldn't have seen other code for it anyway.

On the other hand, this conversation is silly and a bunch of name-calling from both sides. I'm just gonna lock it to prevent further discourse.
