### ISSUE TITLE
Connect4 error

### ISSUE THREAD

**Issue by Beast-0001** [dragonfire535/xiao#84]
**Please describe the problem you are having in as much detail as possible:**
Connect4 isn't working. I've tried to use this command in my own bot with the same command handler but it never worked. I challenged my friend and he said yes but it didn't start the game. 

**Further details:**
- Version: Latest
- Priority this issue should have – please be realistic and elaborate if possible:

- [ X] I found this issue while self-hosting the bot.
  - Node.js version: LAtest
  - Commit hash: Latest
  - Operating system:Windows

**Comment by dragonfire535** [comment]
Non-reproducible self-hosting issues are outside of the scope of this issue tracker. Chances are, it's a you problem. Something you did to the code made it malfunction, and I can't assist with that. Sorry.

**Comment by Beast-0001** [comment]
Can you please add me on discord? Da Beast#9514 I'll show you the code on there
