### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by adgjmptw2** [dragonfire535/xiao#89]
![image](https://user-images.githubusercontent.com/41006577/108243759-cab52d80-7191-11eb-90d5-3a7cd07a76d0.png)
but bot is offline and not working

**Comment by dragonfire535** [comment]
**Non-reproducible self-hosting issues are outside of the scope of this issue tracker. Chances are, it's a you problem. Something you did to the code made it malfunction, and I can't assist with that. Sorry.**
