### ISSUE TITLE
Hi i have found a problem while trying the bot, The Bot won't show on the server and won't actived not even the mention can find the bot i request the bot to be removed from my server .

### ISSUE THREAD

**Issue by Phantom02** [dragonfire535/xiao#9]
*Found a problem with the Bot for Discord server

Problem:

The bot won't show itself
The mention can't find the Bot
Can't delete the Bot 
Can't contact the Bot

Irequest the problem to be fixed immediately Thankyou~

**Comment by dragonfire535** [comment]
> Note: The bot is no longer available for invite.

Right in the README, heh.

**Comment by dragonfire535** [comment]
Bot is available for invite again my dude.

**Comment by Phantom02** [comment]
XD
