### ISSUE TITLE
Hey im getting an error message when i do "npm i --production"

### ISSUE THREAD

**Issue by BankruptKat** [dragonfire535/xiao#90]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/Commando.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
It would be really helpful if u could solve this
Thank You

**Comment by dragonfire535** [comment]
**Non-reproducible self-hosting issues are outside of the scope of this issue tracker. Chances are, it's a you problem. Something you did to the code made it malfunction, and I can't assist with that. Sorry.**
